version: "3.0"

services:
    redis:
        image: redis:alpine
        container_name: lazyseeker-redis

    mysql:
        image: mysql:5.7
        container_name: lazyseeker-mysql
        working_dir: /application
        volumes:
            - .:/application:delegated
            - ./data/mysql:/var/lib/mysql:delegated
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_DATABASE=lazyseeker
            - MYSQL_USER=lazyseeker
            - MYSQL_PASSWORD=lazyseeker

    webserver:
        build: docker/nginx
        container_name: lazyseeker-webserver
        working_dir: /application
        volumes:
            - .:/application:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
        ports:
            - "8080:80"

    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        container_name: lazyseeker-php-fpm
        working_dir: /application
        volumes:
            - .:/application:delegated
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini:delegated
